package com.training.service;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.training.business.bean.PurchaseBean;
import com.training.dao.PurchaseDataAccess;

@Service
@Transactional
public class PurchaseServiceImpl implements PurchaseService {

	private static Logger LOGGER = LoggerFactory.getLogger(PurchaseServiceImpl.class);

	@Autowired
	private PurchaseDataAccess purchaseDataAccess;

	/**
	 * METHOD DESCRIPTION:
	 * This method is used to insert purchase details data into the purchase table.
	 * The transaction ID is generated using the actual purchase primary key
	 * generated by the database.
	 *
	 * Logic:
	 * 1. Save purchase details.
	 * 2. Database generates purchaseId.
	 * 3. Generate transactionId using purchaseId.
	 * 4. Update transactionId in purchase table.
	 *
	 * @param purchaseBean
	 * @return purchaseBean
	 * @throws Exception
	 */
	@Override
	public PurchaseBean addPurchaseDetails(PurchaseBean purchaseBean) throws Exception {

		LOGGER.info("Inside addPurchaseDetails method");

		// Step 1: Save purchase first.
		// Database will generate the purchaseId.
		PurchaseBean savedPurchaseBean = purchaseDataAccess.savePurchaseDetail(purchaseBean);

		// Step 2: Get the actual purchaseId generated by the database.
		Integer purchaseId = savedPurchaseBean.getPurchaseId();

		// Step 3: Generate transactionId using the actual purchaseId.
		String transactionId = transactionIdGenerator(
				savedPurchaseBean.getVendorName(),
				savedPurchaseBean.getMaterialCategoryId(),
				savedPurchaseBean.getPurchaseDate(),
				purchaseId);

		// Step 4: Set the generated transactionId.
		savedPurchaseBean.setTransactionId(transactionId);

		// Step 5: Update transactionId in the purchase table.
		return purchaseDataAccess.updateTransactionId(savedPurchaseBean);
	}

	/**
	 * METHOD DESCRIPTION:
	 * This method is used to generate the transaction id as per logic:
	 *
	 * P_first 3 characters of vendor name_purchase date in MMddyyyy format_
	 * first 3 characters of material category purchased_primary key of purchase table
	 *
	 * Example:
	 * P_AMA_09052026_ELE_16
	 *
	 * @param vendorName
	 * @param materialCategoryName
	 * @param purchaseDate
	 * @param purchaseId
	 * @return String
	 */
	private String transactionIdGenerator(
			String vendorName,
			String materialCategoryName,
			Date purchaseDate,
			Integer purchaseId) {

		String vendorPrefix = safePrefix(vendorName);
		String categoryPrefix = safePrefix(materialCategoryName);
		String datePart = new SimpleDateFormat("MMddyyyy", Locale.ENGLISH).format(purchaseDate);

		return "P_" + vendorPrefix + "_" + datePart + "_" + categoryPrefix + "_" + purchaseId;
	}

	/**
	 * Returns the first three characters after removing spaces.
	 */
	private String safePrefix(String value) {

		if (value == null) {
			return "NA";
		}

		String clean = value.trim().replaceAll("\\s+", "");

		if (clean.length() >= 3) {
			return clean.substring(0, 3).toUpperCase(Locale.ENGLISH);
		}

		return clean.toUpperCase(Locale.ENGLISH);
	}
}