server.port=8090

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/inventorydb?useSSL=false&serverTimezone=UTC
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=03072004

spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# IF You are using this 1st Time kindly Change the ddl mode to [create] ,
#so that it would automatically pick the data from  import.sql and insert into database by firing insert query
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
spring.jpa.show-sql=true

# ================= MATERIAL SERVICE =================

MaterialServiceConsumer.serviceURL=http://localhost:8089

MaterialCategoryConsumer.apiURL=/material/controller/getMaterialCategories
MaterialCategoryConsumer.apiURLForById=/material/controller/getMaterialCategoryById/

MaterialTypeConsumer.apiURL=/type/controller/getTypeDetails
MaterialTypeConsumer.apiURLByCategoryId=/type/controller/getTypeDetailsByCategoryId/

UnitServiceConsumer.apiURL=/unit/controller/getUnitDetails
UnitServiceConsumer.apiURLByCategoryId=/unit/controller/getUnitsByCategoryId/

# ================= VENDOR SERVICE =================
VendorServiceConsumer.serviceURL=http://localhost:8087
VendorServiceConsumer.apiURL=/vendor/controller/getVendors

# First Start vendor microservice then  material microservice then
# inevntory service and then start react application